### ISSUE TITLE
插件载入失败

### ISSUE THREAD

**Issue by SilverLiningSL** [MaxChang3/hexo-bilibili-card#1]
`Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/silverlining/hexo/node_modules/hexo-bilibili-card/lib/bili.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/silverlining/hexo/node_modules/hexo/lib/hexo/index.js:219:21)
    at /Users/silverlining/hexo/node_modules/hexo-bilibili-card/index.js:5:14
    at fs.readFile.then.script (/Users/silverlining/hexo/node_modules/hexo/lib/hexo/index.js:232:12)
    at tryCatcher (/Users/silverlining/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:559:17)
    at formatNunjucksError (/Users/silverlining/hexo/node_modules/hexo/lib/extend/tag.js:102:13)
    at Promise.fromCallback.catch.err (/Users/silverlining/hexo/node_modules/hexo/lib/extend/tag.js:124:34)
    at tryCatcher (/Users/silverlining/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/silverlining/hexo/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/silverlining/hexo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/silverlining/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/silverlining/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/silverlining/hexo/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
`

**Comment by maxchang3** [comment]
是否使用npm安装？
```
npm i hexo-bilibili-card
```
若没有的话，请尝试使用npm安装。
或者
请在hexo目录/node_modules/hexo-bilibili-card
使用`npm i`
或在全局使用`npm i request -g`安装request库。

**Comment by MaxChang3** [comment]
Close #1
